
services:
  db:
    image: postgres:16-alpine
    container_name: idk-postgres
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U myuser -d mydb || exit 1"]
        interval: 10s
        timeout: 10s
        retries: 10
        start_period: 30s   


  redis:
    image: redis:7-alpine
    container_name: idk-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  mongo:
    image: mongo:6.0
    container_name: idk_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 40s

  minio:
    image: minio/minio
    container_name: idk_minio
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 60s

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: idk_rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
      RABBITMQ_ERLANG_COOKIE: "idk_super_secret_cookie_123" 
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq 
    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics -q ping || exit 1"]
      interval: 10s
      timeout: 30s
      retries: 15
      start_period: 120s

  app:
    build: .
    container_name: idk-app
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql+asyncpg://myuser:mypassword@db:5432/mydb
      REDIS_URL: redis://redis:6379/0
      MONGODB_URL: mongodb://admin:admin@mongo:27017/idk_mongo?authSource=admin
      MINIO_ENDPOINT: minio:9000
      MINIO_ACCESS_KEY: admin
      MINIO_SECRET_KEY: admin123
      MINIO_SECURE: "false"
      RABBITMQ_URL: amqp://admin:admin@rabbitmq:5672/
      RABBITMQ_EXCHANGE: chat_exchange
      RABBITMQ_QUEUE: notifications
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      mongo:
        condition: service_healthy
      minio:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

volumes:
  mongo_data:
  minio_data:
  postgres_data:
  rabbitmq_data: